"""create initial tables

Revision ID: 30fdea0ce3b3
Revises: 
Create Date: 2026-10-01 12:48:23.135202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30fdea0ce3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('min_stars', sa.Integer(), nullable=False),
    sa.Column('min_forks', sa.Integer(), nullable=False),
    sa.Column('require_license', sa.Boolean(), nullable=False),
    sa.Column('selected_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('html_url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stargazers_count', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('readme', sa.Text(), nullable=False),
    sa.Column('owner_avatar_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_news_articles',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_news_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q', sa.String(length=512), nullable=False),
    sa.Column('hl', sa.String(length=20), nullable=False),
    sa.Column('gl', sa.String(length=10), nullable=False),
    sa.Column('ceid', sa.String(length=50), nullable=False),
    sa.Column('when', sa.String(length=10), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=False),
    sa.Column('intitle', sa.String(length=255), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_videos')
    op.drop_table('youtube_config')
    op.drop_table('google_news_config')
    op.drop_table('google_news_articles')
    op.drop_table('github_repos')
    op.drop_table('github_config')
    # ### end Alembic commands ###
